name: phpstan-analysis
run-name: ${{ github.actor }} is running phpstan
on: [push]
jobs:
  start-phpstan:
    runs-on: windows-2022      
    steps:
        - uses: actions/checkout@v3
        - uses: php-actions/composer@v6
        - run: .\vendor\bin\phpstan analyse . --level 1