name: phpstan-analysis
run-name: ${{ github.actor }} is running phpstan
on: [push]
jobs:
  start-phpstan:
    runs-on: ubuntu-latest      
    steps:
        - uses: actions/checkout@v3
        - uses: php-actions/composer@v6
        - run: ./vendorµ/bin/phpstan analyse projet --level 1