name: phpstan-analysis
run-name: ${{ github.actor }} is running phpstan
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
        - uses: actions/checkout@v3
        - 
          name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
        - 
          name: run phpstan
          run:  php ./vendor/bin/phpstan analyse projet --level 0
  build:
    needs: test 
    runs-on: ubuntu-latest      
    steps:
        - uses: actions/checkout@v3
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        #  with:
        #    username: ${{ secrets.DOCKERHUB_USERNAME }}
        #    password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: syremios/app

  deploy:
    needs: build 
    runs-on: ubuntu-latest      
    steps:
      - run: echo "Deploy project"